apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml

helmCharts:
- name: secrets-store-csi-driver
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: 1.4.1
  releaseName: secrets-store-csi-driver
  namespace: kube-system
  valuesInline:
    linux:
      providersDir: "/var/run/secrets-store-csi-providers"
- name: vault
  namespace: vault-server
  releaseName: vault-server
  repo: https://helm.releases.hashicorp.com
  valuesInline:
    csi:
      daemonSet:
        providersDir: /var/run/secrets-store-csi-providers
      enabled: true
    global:
      openshift: true
    injector:
      enabled: false
    server:
      enabled: false
  version: 0.27.0

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: vault-server-csi-provider
    path: daemonset-patch.yaml
