apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    enable-route: "true"
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: "{{ .Values.serviceName }}-{{ .Values.servingRuntime }}"
    opendatahub.io/template-name: "{{ .Values.servingRuntime }}"
    openshift.io/display-name: "{{ .Values.serviceName }}"
  name: "{{ .Values.serviceName }}"
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - "--served-model-name={{ .Values.serviceName }}"
        - '--distributed-executor-backend=mp'
        - "--tensor_parallel_size={{ .Values.GPUCount }}"
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
        - --trust-remote-code
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm@sha256:e14cae9114044dc9fe71e99c3db692a892b2caffe04283067129ab1093a7bde5'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
