config:
  name: continue-config
  model:
    name: qwen25-coder-model-server
    project: continue-dev2-project
    domain: apps.rosa-rhoai-3.3nih.p1.openshiftapps.com

workspace:
  name: continue-workspace