apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.runner.name }}"
{{- if .Values.runner.annotations }}
  annotations:
{{- toYaml .Values.runner.annotations | nindent 4 }}
{{- end }}
data:
  requirements.yaml: |
    ---
    {{- if and .Values.requirements.roles (not (empty .Values.requirements.roles)) }}
    roles:
    {{- range .Values.requirements.roles }}
      - name: "{{ .name }}"
        src: "{{ .repo }}"
        scm: git
        version: main
        path: "{{ .name }}"
    {{- end }}
    {{ end }}
    collections:
    {{- range .Values.requirements.collections }}
      - name: "{{ .name }}"
        {{- if .source }}
        source: "{{ .source }}"
        {{- end }}
        {{- if .type }}
        type: "{{ .type }}"
        {{- end }}
        {{- if .version }}
        version: "{{ .version }}"
        {{- end }}
    {{- end }}

  playbook.yaml: |
    ---
    - name: "Run {{ .Values.runner.name }} Playbook"
      hosts: localhost
      connection: local
      gather_facts: yes
      collections:
      {{- range .Values.requirements.collections }}
        - "{{ .name }}"
      {{- end }}
      vars:
        api_url: "https://kubernetes.default.svc"
        token: "{{ `{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}` }}"
        validate_certs: false
{{ toYaml .Values.additionalVars | indent 8 }}
      roles:

      {{- if and .Values.requirements.roles (not (empty .Values.requirements.roles)) }}
      {{- range .Values.requirements.roles }}
        - "{{ .name }}"
      {{- end }}
      {{ end }}

      {{- if and .Values.requirements.collections (not (empty .Values.requirements.collections)) }}
      {{- range .Values.requirements.collections }}
      {{- if and .roles (not (empty .roles)) }}
      {{- range .roles }}
        - "{{ .name }}"
      {{- end }}
      {{- end }}
      {{- end }}
      {{ end }}
