{{ if .Values.initialJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.runner.name }}-job"
{{- if .Values.runner.annotations }}
  annotations:
{{- toYaml .Values.runner.annotations | nindent 4 }}
{{- end }}
spec:
  template:
    spec:
      serviceAccountName: "{{ .Values.runner.name }}-ansible-runner"
      containers:
      - name: "{{ .Values.runner.name }}-job"
        image: "{{ .Values.runner.image }}"
        command: ["/bin/bash", "-c"]
        args:
          - |
            curl -L https://github.com/openshift/rosa/releases/download/v1.2.48/rosa_Linux_x86_64.tar.gz -o rosa.tar.gz;
            tar -xvzf rosa.tar.gz;
            mv rosa /usr/local/bin/rosa;
            chmod +x /usr/local/bin/rosa;
            pip install ansible;
            pip install openshift;
            ls -la /etc/ansible
            ansible-galaxy install -r /etc/ansible/requirements.yaml
            ansible-playbook /etc/ansible/playbook.yaml;
        {{- if hasKey .Values.runner "envFrom" }}
        envFrom:
{{ toYaml .Values.runner.envFrom | indent 10 }}
        {{- end }}
        {{- if hasKey .Values.runner "env" }}
        env:
{{ toYaml .Values.runner.env | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: playbook-volume
          mountPath: /etc/ansible
      volumes:
      - name: playbook-volume
        configMap:
          name: "{{ .Values.runner.name }}"
      restartPolicy: Never
{{ end }}