apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.runner.name }}-ansible-runner"
{{- if .Values.runner.annotations }}
  annotations:
{{- toYaml .Values.runner.annotations | nindent 4 }}
{{- end }}
