apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: eso-secret-store
  namespace: openshift-operators
spec:
  provider:
    azurekv:
      tenantId: "{{ root_vault.tenant-id }}"
      vaultUrl: "{{ root_vault.vault-url }}"
      authSecretRef:
        clientId:
          name: azure-eso-secret
          key: client-id
        clientSecret:
          name: azure-eso-secret
          key: client-secret
