# This RoleBinding associates the 'spark-pod-scheduler' role with the 'jupyter-notebooks' service account.
# It ensures the service account inherits permissions from the role.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-pod-scheduler
  namespace: spark-running-environment
subjects:
  - kind: ServiceAccount
    name: workflow-orchestrator-sa
    namespace: workflow-orchestrator
roleRef:
  kind: Role
  name: spark-pod-scheduler
  apiGroup: rbac.authorization.k8s.io
