---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi-driver
  namespace: openshift-gitops
  annotations:
    # SyncWave Orders 
    # -2 Drivers
    # -1 Operators
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: vault-csi-driver-controller
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/managing-secrets'
    path: 'patterns/secrets-csi-driver/foundational/provider/vault'
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
