kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ .Values.notebookName }}"
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.notebook: 'https://{{ .Values.notebookName }}-{{ .Values.namespace }}.apps.{{ .Values.domain }}/oauth/callback'
