{{- if .Values.enabledCUDA }}
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: CUDA
    notebooks.opendatahub.io/last-size-selection: Custom
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.{{ .Values.domain }}/projects/{{ .Values.namespace }}?notebookLogout={{ .Values.notebookName }}
    opendatahub.io/accelerator-name: migrated-gpu
    openshift.io/description: ''
    openshift.io/display-name: "{{ .Values.notebookName }}"
    notebooks.opendatahub.io/last-image-selection: 'minimal-gpu:2024.1'
    opendatahub.io/username: "admin"
  name: "{{ .Values.notebookName }}"
  labels:
    app: "{{ .Values.notebookName }}"
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: admin
spec:
  template:
    spec:
      containers:
        - name: "{{ .Values.notebookName }}"
          resources:
            limits:
              cpu: '2'
              memory: 45Gi
              nvidia.com/gpu: "{{ .Values.numGPU }}"
            requests:
              cpu: '2'
              memory: 45Gi
              nvidia.com/gpu: "{{ .Values.numGPU }}"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{ .Values.namespace }}/{{ .Values.notebookName }}/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{ .Values.namespace }}/{{ .Values.notebookName }}/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/{{ .Values.namespace }}/{{ .Values.notebookName }}
                --ServerApp.quit_button=False
                --ServerApp.tornado_settings={"user":"admin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.{{ .Values.domain }}","hub_prefix":"/projects/{{ .Values.namespace }}"}
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2024.1'
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: "{{ .Values.notebookName }}"
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
          envFrom:
            - secretRef:
                name: aws-connection-{{ .Values.dataConnectionName }}
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2024.1'
          workingDir: /opt/app-root/src
        - name: oauth-proxy
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46'
          args:
            - --provider=openshift
            - --https-address=:8443
            - --http-address=
            - --openshift-service-account={{ .Values.notebookName }}
            - --cookie-secret-file=/etc/oauth/config/cookie_secret
            - --cookie-expire=24h0m0s
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --upstream=http://localhost:8888
            - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --email-domain=*
            - --skip-provider-button
            - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"{{ .Values.notebookName }}","namespace":"$(NAMESPACE)"}
            - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.{{ .Values.domain }}/projects/{{ .Values.namespace }}?notebookLogout={{ .Values.notebookName }}
      enableServiceLinks: false
      serviceAccountName: "{{ .Values.notebookName }}"
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - name: "{{ .Values.notebookName }}"
          persistentVolumeClaim:
            claimName: "{{ .Values.notebookName }}"
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: "{{ .Values.notebookName }}-oauth-config"
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: "{{ .Values.notebookName }}-tls"
{{- end }}