apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: registry-secret
    template:
      type: generic
      data:
        config.json: |
          {
            "auths": {
              "{{ .dockerregistryurl | toString }}": {
                "username": "{{ .username | toString }}",
                "password": "{{ .password | toString }}",
                "email": "{{ .email | toString }}",
                "auth": "{{ .auth | toString }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: demo
      property: username
  - secretKey: password
    remoteRef:
      key: demo
      property: password
  - secretKey: email
    remoteRef:
      key: demo
      property: email
  - secretKey: dockerregistryurl
    remoteRef:
      key: demo
      property: dockerregistryurl
  - secretKey: auth
    remoteRef:
      key: demo
      property: auth
