apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: github-event-listener
  name: el-github-https
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-github-event-listener
    weight: 100
  wildcardPolicy: None