apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <External_Secret_Name>
  namespace: <namespace>
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-secret-store
    kind: ClusterSecretStore
  target:
    name: <NAME_OF_CREATED_SECRET>
    creationPolicy: Owner
  data:
  - secretKey: <Secret_Key_In_Created_Secret>
    remoteRef:
      key: <AWS_SECRETS_MANAGER_SECRET_NAME>
      property: <THE_SET_AWS_SECRET_KEY>
