apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: managed-secretstore
  namespace: <namespace>
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secret
            key: secret-access-key
