apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hermetic-build-policy
spec:
  podSelector:
    matchLabels:
      hermetic: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
