apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: container-build-pipeline
spec:
  params:
    - name: IMAGE_NAME
    - name: REGISTRY_HOSTNAME
    - name: REGISTRY_NAMESPACE
    - name: IMAGE_TAG
    - name: GITHUB_REPO
    - name: GITHUB_BRANCH
  workspaces:
    - name: source
    - name: varlibcontainers
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GITHUB_REPO)
        - name: revision
          value: $(params.GITHUB_BRANCH)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
      - name: output
        workspace: source

    - name: pre-fetch-dependencies
      params:
        - name: DIRECTORY
          value: '.'
        - name: HERMETIC
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pre-fetch-dependencies
      workspaces:
        - name: source
          workspace: source

    - name: build
      params:
        - name: IMAGE
          value: 'quay.io/$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: BUILD_EXTRA_ARGS
          value: "--layers=true"
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - pre-fetch-dependencies
      taskRef:
        kind: Task
        name: build
      workspaces:
        - name: source
          workspace: source
        - name: varlibcontainers
          workspace: varlibcontainers

    - name: generate-sbom
      params:
        - name: IMAGE
          value: 'quay.io/$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
      runAfter:
        - build
      taskRef:
        kind: Task
        name: generate-signed-sbom
      workspaces:
        - name: source
          workspace: source

    - name: scan-and-sign-sbom
      runAfter:
        - generate-sbom
      taskRef:
        kind: Task
        name: scan-and-sign-sbom
      workspaces:
        - name: source
          workspace: source

    - name: push
      params:
        - name: IMAGE
          value: 'quay.io/$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: BUILD_EXTRA_ARGS
          value: "--layers=true"
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - scan-and-sign-sbom
      taskRef:
        kind: Task
        name: push
      workspaces:
        - name: source
          workspace: source
        - name: varlibcontainers
          workspace: varlibcontainers
