{{- range .Values.teams }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.secrets.admin.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-creds
  data:
  - secretKey: token
    remoteRef:
      key: {{ .name }}-creds
      property: token
---
{{- end }}