---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: kfp-pipeline-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision sha
    - name: gitrepo
      description: The git repo
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata: 
        name: kfp-sync-$(tt.params.gitrevision)
      spec:
        serviceAccountName: openshift-pipelines
        pipelineRef:
          name: kfp-sync-pipeline
        params: 
          - name: GITHUB_REPO
            value: $(tt.params.gitrepo)
          - name: GITHUB_BRANCH
            value: 'main'
        podTemplate:
          securityContext:
            runAsUser: 1000
            fsGroup: 65532
            fsGroupChangePolicy: "OnRootMismatch"
        workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: kfp-pipeline-listener
spec:
  triggers:
    - name: filter-events
      interceptors:
        # - ref:
        #     name: "github"
        #     kind: ClusterInterceptor
        #     apiVersion: triggers.tekton.dev
        #   params:
        #     - name: "eventTypes"
        #       value: ["Push Hook"]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
          - name: "overlays"
            value:
            - key: truncated_sha
              expression: "body.after.truncate(7)"
      bindings:
        - name: gitrevision
          kind: TriggerBinding
          value: $(extensions.truncated_sha)
        - name: gitrepo
          kind: TriggerBinding
          value: "$(body.repository.html_url)"
      template:
        ref: kfp-pipeline-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
    - name: gitrepo
      value: "$(body.repository.html_url)"
