apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kfp-sync-pipeline
spec:
  params:
    - name: GITHUB_REPO
      type: string
    - name: GITHUB_BRANCH
      type: string
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GITHUB_REPO)
        - name: revision
          value: $(params.GITHUB_BRANCH)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
      - name: output
        workspace: source
