apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-secret
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{`{{ .server | toString }}`}}": {
                "username": "{{`{{ .username | toString }}`}}",
                "password": "{{`{{ .password | toString }}`}}",
                "auth": "{{`{{ printf "%s:%s" .username .password | b64enc }}`}}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: demo
      property: username
  - secretKey: password
    remoteRef:
      key: demo
      property: password
  - secretKey: server
    remoteRef:
      key: demo
      property: server
