{{- range .Values.teams }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}-gitops
  labels:
    argocd.argoproj.io/managed-by: {{ .name }}-gitops
---
{{ $name := .name }}
{{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    argocd.argoproj.io/managed-by: {{ $name }}-gitops
---
{{- end }}
{{- end }}
