{{- range .Values.teams }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}-secret-store
  namespace: {{ $.Values.secrets.admin.namespace }}
spec:
  conditions:
    - namespaces:
      {{- range .namespaces }}
      - "{{ . }}"
      {{- end }}
  provider:
    vault:
      server: "http://vault-server-internal.vault-server.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .name }}-creds
          key: "token"
---
{{- end }}