kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: langflow
spec:
  to:
    kind: Service
    name: langflow
    weight: 100
{{ if .Values.securedRoute }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{ end }}
  port:
    targetPort: 8080
  wildcardPolicy: None
