apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: eso-secret-store
  namespace: openshift-operators
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
