{{- if .Values.vault }}
{{- if .Values.vault.enabled }}
{{- if .Values.shared }}
## can move to bools here doing this for temp capability until other charts are refactored
## for new passing methods
{{- if or (eq .Values.shared.enabled "True") (eq .Values.shared.enabled "true") }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "external-argocd-connection-secret"
  namespace: "openshift-gitops"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-external-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: "openshift-gitops-cluster"
  data:
    - match:
        secretKey: "admin.password"
        remoteRef:
          remoteKey: "{{ .Values.cluster_name }}/argocd"
          property: "ARGOCD_TOKEN"
{{- end }}
{{- end }}
{{- end }}
{{- end }}