{{- if .Values.vault }}
{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "internal-argocd-connection-secret"
  namespace: "openshift-gitops"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: "openshift-gitops-cluster"
  data:
    - match:
        secretKey: "admin.password"
        remoteRef:
          remoteKey: "{{ .Values.cluster_name }}/argocd"
          property: "ARGOCD_TOKEN"
{{- end }}
{{- end }}