---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-eventlistener-cluster-role
rules:
- apiGroups:
  - "security.openshift.io"
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clusterinterceptors
  - interceptors
  verbs:
  - list
  - get
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: tekton
roleRef:
  kind: ClusterRole
  name: tekton-eventlistener-cluster-role
  apiGroup: rbac.authorization.k8s.io
