apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.name }}"
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: "{{ .Values.name }}"
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None