apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
  name: {{ include "web-service.fullname" . }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "web-service.fullname" . }}
    weight: 100
  wildcardPolicy: None