apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyspark-jupyter-notebook-work-files
  namespace: workflow-orchestrator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
