apiVersion: v1
kind: Service
metadata:
  name: pyspark-jupyter-notebook
  namespace: workflow-orchestrator
spec:
  type: LoadBalancer
  ports:
  - name: notebook-port
    port: 8888
    targetPort: 8888
  - name: spark-driver-port
    port: 4040
    targetPort: 4040
  selector:
    app: pyspark-jupyter-notebook
