apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: "{{ .Values.name }}"
spec:
  entityOperator:
    {{- if .Values.capacityEnabled }}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - values:
                        - kakfa-capacity
                      key: platform.poc-examples.com/workload-role
                      operator: In
    {{- end }}
    topicOperator: {}
    userOperator: {}
  kafka:
    {{- if .Values.capacityEnabled }}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - values:
                        - kakfa-capacity
                      key: platform.poc-examples.com/workload-role
                      operator: In
    {{- end }}
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.8'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    replicas: 3
    storage:
      type: ephemeral
    version: 3.8.0
  zookeeper:
    {{- if .Values.capacityEnabled }}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - values:
                        - kakfa-capacity
                      key: platform.poc-examples.com/workload-role
                      operator: In
    {{- end }}
    replicas: 3
    storage:
      type: ephemeral