apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .Values.project }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: "Project that holds a Data Science projects resources."
  sourceRepos:
    - '*'
  destinations:
    - namespace: "{{ .Values.project }}"
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: 'Secret'
